name: booksapp
description: booksapp

version: 1.0.0+1

publish_to: "none"

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  dio: ^4.0.1
  webview_flutter: ^3.0.4
  easy_refresh: ^3.0.4+3
  json_annotation: ^4.7.0
  equatable: ^2.0.5
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  hydrated_bloc: ^9.0.0
  file_picker: ^5.2.0+1
  flutter_slidable: ^2.0.0
  package_info_plus: ^3.0.1
  path_provider: ^2.0.11
  crypto: ^3.0.2
  formz: ^0.4.1
  permission_handler: ^10.0.1
  android_path_provider: ^0.3.0
  url_launcher: ^6.1.5
  oktoast: ^3.1.5
  sp_util: ^2.0.3

  helper:
    path: packages/helper
  general_data:
    path: packages/general_data
  general_widgets:
    path: packages/general_widgets
  api:
    path: packages/api
  remote_api:
    path: packages/remote_api
  form_inputs:
    path: packages/form_inputs
  authentication_repository:
    path: packages/authentication_repository
  bloc_transformer:
    path: packages/bloc_transformer
  configuration_repository:
    path: packages/configuration_repository
  event_bus:
    path: packages/event_bus
  mock_api:
    path: packages/mock_api
  environment_variable:
    path: packages/environment_variable
  diagnose_logger:
    path: packages/diagnose_logger
  browser:
    path: packages/browser

  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  build_runner: ^2.2.1
  flutter_gen_runner: ^5.1.0+1
  very_good_analysis: 3.1.0
  bloc_test: ^9.1.0
  mockingjay: ^0.3.0
  mocktail: ^0.3.0
  json_serializable: ^6.5.4

flutter_gen:
  output: lib/gen/
  line_length: 80

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/pems/
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Thin.ttf
    - family: Pingfang
      fonts:
        - asset: assets/fonts/pingfang/PingFang-Regular.ttf
        - asset: assets/fonts/pingfang/PingFang-Light.ttf
          weight: 200
        - asset: assets/fonts/pingfang/PingFang-Bold.ttf
          weight: 500
