name: authentication_repository
description: A new Flutter package project.
version: 0.0.1
homepage:

publish_to: "none"

environment:
  sdk: ">=2.18.4 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.7.0
  equatable: ^2.0.5
  http: ^0.13.5
  oauth2: ^2.0.0
  uni_links: ^0.5.1
  synchronized: ^3.0.0+2
  dio: ^4.0.1
  url_launcher: ^6.1.5

  helper:
    path: ../helper
  general_widgets:
    path: ../general_widgets
  environment_variable:
    path: ../environment_variable
  diagnose_logger:
    path: ../diagnose_logger

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.1
  very_good_analysis: 3.1.0
  json_serializable: ^6.5.4

flutter:
  assets:
    - files/authorization.html
